name: test CI

on:
  push:
    branches: [ develop ]

jobs:

  build:
    name: build_dist
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14x]
    steps:
      - run: npm run build
      - name: cache_dist_without_markdown
        uses: actions/upload-artifact@v3
        with:
          name: dist
          path: |
            dist
            !dist/**/*.md
          retention-days: 3

  build:
    name: deploy
    needs: build_dist
    runs-on: ubuntu-latest
    steps:
      - name: obtain_dist
        uses: actions/download-artifact@v3
        with:
          name: dist
      - run: scp -o StrictHostKeyChecking=no -P ${{secrets.PORT}} -r dist ${{secrets.USER}}:/data