name: test CI

on:
  push:
    branches: [ develop ]

jobs:

  build:
    name: build_dist
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14x]
    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          ref: 'develop'
      - run: npm install
      - run: npm run build
      - name: cache_dist_without_markdown
        uses: actions/upload-artifact@v3
        with:
          name: dist
          path: |
            dist
            !dist/**/*.md
          retention-days: 3

  depoly:
    name: deploy
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: obtain_dist
        uses: actions/download-artifact@v3
        with:
          name: dist
        env:
          WORD_DIR: ${{secrets.WORD_DIR}}
          DO: ${{secrets.DO}}
      - run: pwd
      - run: cd /home/runner/work/test/test
      - run: |
          ls -l
          sshpass -p ${{secrets.SECRETS}} ssh -o StrictHostKeyChecking=no -P ${{secrets.PORT}} ${{secrets.USER}} "rm -rf ${WORD_DIR}/*"
      - run: sshpass -p ${{secrets.SECRETS}} scp -o StrictHostKeyChecking=no -P ${{secrets.PORT}} -r ./* ${{secrets.USER}}:${WORD_DIR}
      - run: sshpass -p ${{secrets.SECRETS}} ssh -o StrictHostKeyChecking=no -P ${{secrets.PORT}} ${{secrets.USER}} "${DO}"